// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var Personnummer = require("../src/Personnummer.bs.js");

Jest.testAll("validates personnummer", {
      hd: [
        "1212121212",
        /* Valid */{
          _0: "1212121212"
        }
      ],
      tl: {
        hd: [
          "1212121213",
          /* Invalid */0
        ],
        tl: {
          hd: [
            "121212121212",
            /* Valid */{
              _0: "121212121212"
            }
          ],
          tl: {
            hd: [
              "191212121212",
              /* Valid */{
                _0: "191212121212"
              }
            ],
            tl: {
              hd: [
                "201212121212",
                /* Valid */{
                  _0: "201212121212"
                }
              ],
              tl: /* [] */0
            }
          }
        }
      }
    }, (function (param) {
        return Jest.Expect.toEqual(param[1], Jest.Expect.expect(Personnummer.Validate.make(param[0])));
      }));

Jest.testAll("parse", {
      hd: [
        "12 12 12 12 12",
        /* Valid */{
          _0: {
            year: "12",
            month: "12",
            day: "12",
            gender: /* Male */0,
            placeOfBirth: /* Stockholm */0
          }
        }
      ],
      tl: {
        hd: [
          "12 12 12 12 13",
          /* Invalid */0
        ],
        tl: /* [] */0
      }
    }, (function (param) {
        return Jest.Expect.toEqual(param[1], Jest.Expect.expect(Personnummer.Parse.make(param[0])));
      }));

Jest.testAll("place of birth", {
      hd: [
        "Stockholm",
        0,
        /* Stockholm */0
      ],
      tl: {
        hd: [
          "Stockholm",
          13,
          /* Stockholm */0
        ],
        tl: {
          hd: [
            "Uppsala",
            14,
            /* Uppsala */1
          ],
          tl: {
            hd: [
              "Södermanland",
              17,
              /* Sodermanland */2
            ],
            tl: {
              hd: [
                "Östergötaland",
                22,
                /* Ostergotaland */3
              ],
              tl: {
                hd: [
                  "Jönköping",
                  25,
                  /* Jonkoping */4
                ],
                tl: {
                  hd: [
                    "Kronoberg",
                    27,
                    /* Kronoberg */5
                  ],
                  tl: {
                    hd: [
                      "Kalmar",
                      30,
                      /* Kalmar */6
                    ],
                    tl: {
                      hd: [
                        "Gotland",
                        32,
                        /* Gotland */7
                      ],
                      tl: {
                        hd: [
                          "Blekinge",
                          33,
                          /* Blekinge */8
                        ],
                        tl: {
                          hd: [
                            "Kristianstad",
                            36,
                            /* Kristianstad */9
                          ],
                          tl: {
                            hd: [
                              "Malmohus",
                              40,
                              /* Malmohus */10
                            ],
                            tl: {
                              hd: [
                                "Halland",
                                46,
                                /* Halland */11
                              ],
                              tl: {
                                hd: [
                                  "Goteborg",
                                  49,
                                  /* Goteborg */12
                                ],
                                tl: {
                                  hd: [
                                    "Alvsborg",
                                    56,
                                    /* Alvsborg */13
                                  ],
                                  tl: {
                                    hd: [
                                      "Skaraborg",
                                      60,
                                      /* Skaraborg */14
                                    ],
                                    tl: {
                                      hd: [
                                        "Varmland",
                                        63,
                                        /* Varmland */15
                                      ],
                                      tl: {
                                        hd: [
                                          "Orebro",
                                          67,
                                          /* Orebro */16
                                        ],
                                        tl: {
                                          hd: [
                                            "Vastmanland",
                                            69,
                                            /* Vastmanland */17
                                          ],
                                          tl: {
                                            hd: [
                                              "Kopparberg",
                                              72,
                                              /* Kopparberg */18
                                            ],
                                            tl: {
                                              hd: [
                                                "Gavleborg",
                                                76,
                                                /* Gavleborg */19
                                              ],
                                              tl: {
                                                hd: [
                                                  "Vasternorrland",
                                                  79,
                                                  /* Vasternorrland */20
                                                ],
                                                tl: {
                                                  hd: [
                                                    "Jamtland",
                                                    83,
                                                    /* Jamtland */21
                                                  ],
                                                  tl: {
                                                    hd: [
                                                      "Vasterbotten",
                                                      87,
                                                      /* Vasterbotten */22
                                                    ],
                                                    tl: {
                                                      hd: [
                                                        "Norrbotten",
                                                        90,
                                                        /* Norrbotten */23
                                                      ],
                                                      tl: {
                                                        hd: [
                                                          "Extra number",
                                                          65,
                                                          /* ExtraNumber */24
                                                        ],
                                                        tl: {
                                                          hd: [
                                                            "Extra number",
                                                            74,
                                                            /* ExtraNumber */24
                                                          ],
                                                          tl: {
                                                            hd: [
                                                              "Extra number",
                                                              97,
                                                              /* ExtraNumber */24
                                                            ],
                                                            tl: {
                                                              hd: [
                                                                "Unknown",
                                                                100,
                                                                /* Unknown */25
                                                              ],
                                                              tl: /* [] */0
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }, (function (param) {
        return Jest.Expect.toBe(param[2], Jest.Expect.expect(Personnummer.PlaceOfBirth.make(param[1])));
      }));

/*  Not a pure module */
